### Cadastrar livro
POST http://localhost:5195/api/pressao/cadastrar
Content-Type: application/json

{
    "id":1,
    "nomePaciente":"Ana Souza",
    "pressaoMaxima":118,
    "pressaoMinima":76,
    "classificacao":"Normal",
    "dataRegistro":"2026-06-15T08:30:00"
}

### Listar livros
GET http://localhost:5195/api/pressao/listar

### Deletar da lista
PUT http://localhost:5195/apiteste/livros/alterar/83d0f93b-4fae-4e3b-bc62-3ff656fea2bc